/*
*			-={AWG}=- DayZ HIVE
*			Mission Briefing
*			Author: Anzu
*/
// since we're working with the player object here, make sure it exists
waitUntil { !isNull player };
waitUntil { player == player };

// briefing entries

_log_briefing = player createDiaryRecord ["Diary", ["VIP Gear for Donors", "<br/>Donations are what keeps our community and servers alive =)  Donation Options are available on our website.<br/><br/>http://www.AnzusWarGames.info<br/><br/>We do appreciate your generous donation, no matter how much. Those who donate will get VIP loadouts that they will spawn with each time they start a new life.  VIPs may choose from a list of items that they will be able to spawn with each time they start a new life in-game.<br/><br/>  VIP options are available as follows:<br/>   == LEVEL 1 (donate atleast $5 a month): ==<br/>    -- Primary Weapons: --<br/>     AK-74<br/>     AKM<br/>     AKS-74 Kobra<br/>     AKS-74u<br/>     M16A2<br/>     M4A1 CCO<br/>     Double-Barreled Shotgun<br/>     Winchester 1866<br/>     Lee Enfield<br/>     M4A1 Holo<br/>    -- Secondary Weapons: --<br/>     M1911<br/>     Makarov PM<br/>     Revolver<br/>     M9<br/>     <br/>    Equipment:<br/>     Water Bottle<br/>     Soda Can (Coke)<br/>     Soda Can (Pepsi)<br/>     Can (Baked Beans)<br/>     Can (Pasta)<br/>     Can (Sardines)<br/>     Cooked Meat<br/>     Bandage<br/>     Morphine Auto-Injector<br/>     Painkillers<br/>     Epi-pen<br/>     Blood Bag<br/>     Heat Pack <br/>     Road Flare<br/>     Smoke Grenade<br/>     Binoculars<br/>     NV Goggles<br/>     Compass <br/>     Entrenching Tool<br/>(Click arrow in bottom-right corner for Next Page)<br/>     Flashlight<br/>     Flashlight (Military)<br/>     Watch<br/>     Map<br/>     Hunting Knife<br/>     Matches<br/>    Backpacks:<br/>     Czech Vest Pouch (6 slots)<br/>     Patrol Pack (Coyote) (8 slots)<br/>     Assault Pack (ACU) (12 slots)<br/>     Czech Backpack (16 slots)<br/>     Alice Pack (20 slots)<br/>    Skins:<br/>     Survivor<br/>     Survivor (Female)<br/>     Camo<br/>     Ghillie<br/>     Rocket<br/>     Bandit<br/>     Bandit (Female)<br/>     Hero<br/>   == LEVEL 2 (donate $10 per month or more, all Level 1 gear is included): ==<br/>    -- Primary Weapons: --<br/>     CZ550<br/>     M24<br/>     Mk 12 SPR<br/>     G36C SD Eotech<br/>     M4A1 AIM SD<br/>    -- Secondary Weapons: --<br/>     M9SD<br/>     MakarovSD<br/>    Equipment:<br/>     GPS<br/>    Backpacks:<br/>     Coyote Backpack (24 slots)"]];

_log_briefing = player createDiaryRecord ["Diary", ["Mission Editors", "<br/>AWG's Mission Editors: Anzu and Tactical Force<br/>====================<br/>Contact us on Steam<br/>====================<br/>Tactical Force: pontiacman86<br/>Anzu: tylenol187<br/>You can drop us a line with suggestions or give us props :)"]];

_log_briefing = player createDiaryRecord ["Diary", ["-={AWG}=- Epic Bases", "<br/>  Our mission editors have added custom-designed Epic Bases into the map at various locations.  These bases serve as posts where survivors and bandits can fight to capture and defend.  We encourage you all to go out and explore every corner of the map and find the Epic Bases.  Some of the bases have gear boxes we've added in for supplies.  Most of them are pretty huge in scale and will be obvious when you find them, but if you aren't sure where they are try asking another player ;)"]];

_log_briefing = player createDiaryRecord ["Diary", ["SERVER RULES - PLEASE READ!", "<br/>===================================================================<br/>IF RULES AREN'T OBEYED IT WILL RESULT IN KICK/TEMP BAN/PERMABAN!<br/>===================================================================<br/>Our rules are fair and simple:<br/>  1. RESPECT other players, especially admins! (Rivalry is fine, but do when you blatantly disrespect another player in an abusive manner you will be banned.<br/>  2. Do NOT cheat or hack or run any mods and/or addons that are not explicitly required to join our server! If you do, you will be permabanned, submitted GUID to global ban list, AND your IP will be traced and an abuse report will be sent to your Internet Service Provider.<br/>  3. Do NOT advertise for other servers or clans, or try to recruit people for another clan while on our servers.<br/>  4. Do NOT hang out with cheaters or ask them to give you things, you will banned along with the cheater.<br/>  5. Do NOT talk in voice on Side or Global Chat.  You will be warned the first time, do it again and you may get kicked or banned.<br/><br/>  If you catch people breaking these rules and there is no admin available at the time to ban them, please post a Ban Request on our forums in the Bans/Unbans section.<br/><br/>http://AnzusWarGames.info/forums"]];

_log_briefing = player createDiaryRecord ["Diary", ["Admins", "<br/>CURRENT SENIOR ADMINS:<br/>  Anzu<br/>  Tactical Force<br/>  Swany<br/>  Suicide<br/>  KernalPanic<br/>  Rezel<br/>  Jordan<br/>  Superxpdude<br/>  Yellowjacket<br/>  Cheknov<br/><br/>CURRENT JUNIOR ADMINS:<br/>  TigerChan<br/>  Heavy Smoker<br/>  Venner<br/><br/>==============================================================================================================<br/>If you have a problem with cheaters/griefers and there is no admin available, please message one of us on Steam or post on our forums.<br/>  One of us is usually always online.<br/>==============================================================================================================<br/>Contact us on Steam<br/>====================<br/>  Tactical Force: pontiacman86<br/>  Anzu: tylenol187"]];
